server:
  port: 8000
zuul:
  prefix: /api
  routes:
    sending:
      path: /sender/**
      url: http://localhost:8080/
    receiving:
      path: /receiver/**
      url:  http://localhost:8081/
    test:
      path: /test
      url: http://www.wp.pl
  endpoints:
    trace:
      sensitive: false
  ribbon:
    eureka:
      enabled: false
