server:
  port: 8000
zuul:
  # register services by hand
  ignoredServices: '*'
  prefix: /api
  routes:
    sending:
      path: /sender/**
      serviceId: sender
      strip-prefix: false
    receiving:
      path: /receiver/**
      serviceId: receiver
      strip-prefix: false
  endpoints:
    trace:
      sensitive: false
    routes:
      sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
